### ISSUE TITLE
Checkbox not working

### ISSUE THREAD

**Issue by Sp3EdeR** [copperspice/doxypressapp#2] opened 2019-10-25 13:07 UTC
When toggling the Build Settings -> Dot ->Dot (Part 1) -> Collaboration graph option, the saved json file always contains the "true" value for the corresponding setting.

**Comment by Sp3EdeR** [comment] 2019-10-25 13:15
I think the same happens with the "Include graph" and "Included by graph" options.

**Comment by agserm** [comment] 2019-10-25 14:20
Thanks for the report, we will take a look at this.

**Comment by bgeller** [comment] 2019-10-30 02:56
Our main office is located in Northern California and our local electric company turned power off for multiple days in an attempt to prevent fires. We are about to lose power again and in the process of shutting down all the computers to prevent any internal issues. 

Thank you for reporting these issues and we will address them shorty. Thank you for your patience. 

Barbara

**Comment by bgeller** [comment] 2019-11-03 23:38
Thanks for catching this. I had a look at this and see the overall issue.  The problem is actually related to a UI carry over. There are few fields duplicated on the Setup ( tab one ) which make sense.  Some of the others may not.

Can you have a look at the topic "Diagrams" on tab one.  We were discussing this with the team and our preference is to remove the check boxes (  for Class Graph, etc ) and add a button which would take the user to the Build Settings, Dot 1 screen. This would solve your issue and I think be more intuitive.  Do you have any strong objections?

Barbara

**Comment by Sp3EdeR** [comment] 2019-11-04 12:57
Hello Barbara,

I think I would remove the whole Diagrams page from the first tab. For me, the diagram settings seem like a part of the build settings.

My personal view on the UI organization:
I think the best design would be to merge the Project category into the "Build Settings" tab as the first option and the Output category into the "Output Formats" tab as the first category. The first tab seems to me like an arbitrary emphasis for a few of the options, which is probably insufficient for some projects. The topic listing is also apparently a hierarchical tree, so that could also be used for emphasizing some configs.

A different organization that is probably stronger could be to split build options between source definition / parsing options vs. options that specify or tweak the generated information.

Best regards,
Speeder

**Comment by agserm** [comment] 2019-11-04 17:46
We have updated the DoxyPressApp UI to remove the Diagrams page completely from the first tab. This should solve the checkbox issue you initially reported, so I will close this ticket. We have it on our watchlist to redesign the remainder of these items and reorganize the UI in this area. Thanks for your report.

**Closed as completed by agserm** 2019-11-04 17:46 UTC
